version: '3.7'

services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    ports:
      - "8081:8080"
      - "50000:50000"
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"
    container_name: jenkins

volumes:
  jenkins_home:
